use std::{fmt, path::PathBuf, time::SystemTime};

use secrecy::{ExposeSecret, SecretString};

use crate::{Result, dataset::normalize_create_network};

/// Public development dataset shared by the Extrittio Edge border router and the
/// ESP32-C6 OpenThread example. It is intentionally unsuitable for a private
/// or production Thread mesh.
pub const DEFAULT_DEVELOPMENT_DATASET_TLVS: &str = "4a0300000c0e08000000000001000035060004001fffe00708fd35344133d1d73e04105e9b9b360f80b88be2603fb0135c8d650c0402a0f7f800030000190208a6c9c979b7f141590510b7fd07e5ce003cbe047f62c0b8bd7349031065787472697474696f2d63362d64657601027880";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadStatus {
    pub role: ThreadRole,
    pub network_name: Option<String>,
    pub channel: Option<u16>,
    pub pan_id: Option<String>,
    pub extended_pan_id: Option<String>,
    pub mesh_local_prefix: Option<String>,
    pub addresses: Vec<String>,
}

impl ThreadStatus {
    /// Whether the Thread interface currently participates in an attached
    /// network role. A running OTBR can be available while still disabled or
    /// detached.
    #[must_use]
    pub fn is_attached(&self) -> bool {
        self.role.is_attached()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ThreadRole {
    Disabled,
    Detached,
    Child,
    Router,
    Leader,
    Unknown(String),
}

impl ThreadRole {
    #[must_use]
    pub fn from_otbr(value: String) -> Self {
        match value.as_str() {
            "disabled" => Self::Disabled,
            "detached" => Self::Detached,
            "child" => Self::Child,
            "router" => Self::Router,
            "leader" => Self::Leader,
            _ => Self::Unknown(value),
        }
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Disabled => "disabled",
            Self::Detached => "detached",
            Self::Child => "child",
            Self::Router => "router",
            Self::Leader => "leader",
            Self::Unknown(value) => value,
        }
    }

    #[must_use]
    pub fn is_attached(&self) -> bool {
        matches!(self, Self::Child | Self::Router | Self::Leader)
    }
}

/// Parameters used to form a completely new Thread network.
///
/// The optional network key is held in zeroizing memory and is redacted from
/// debug output. Omitted identifiers and credentials are generated by
/// OpenThread rather than inherited from the previous operational dataset.
#[derive(Clone)]
pub struct CreateNetwork {
    network_name: String,
    channel: Option<u16>,
    pan_id: Option<String>,
    extended_pan_id: Option<String>,
    network_key: Option<SecretString>,
}

impl CreateNetwork {
    /// Validates and normalizes all caller-controlled network parameters.
    ///
    /// Network names must already be in their canonical form; leading or
    /// trailing whitespace is rejected rather than silently changing the
    /// network that will be created.
    pub fn new(
        network_name: String,
        channel: Option<u16>,
        pan_id: Option<String>,
        extended_pan_id: Option<String>,
        network_key: Option<String>,
    ) -> Result<Self> {
        let normalized =
            normalize_create_network(network_name, channel, pan_id, extended_pan_id, network_key)?;
        Ok(Self {
            network_name: normalized.network_name,
            channel: normalized.channel,
            pan_id: normalized.pan_id,
            extended_pan_id: normalized.extended_pan_id,
            network_key: normalized.network_key.map(SecretString::new),
        })
    }

    pub(crate) fn network_name(&self) -> &str {
        &self.network_name
    }

    pub(crate) fn channel(&self) -> Option<u16> {
        self.channel
    }

    pub(crate) fn pan_id(&self) -> Option<&str> {
        self.pan_id.as_deref()
    }

    pub(crate) fn extended_pan_id(&self) -> Option<&str> {
        self.extended_pan_id.as_deref()
    }

    pub(crate) fn network_key(&self) -> Option<&str> {
        self.network_key
            .as_ref()
            .map(ExposeSecret::expose_secret)
            .map(String::as_str)
    }
}

pub(crate) struct ValidatedCreateNetwork {
    pub(crate) network_name: String,
    pub(crate) channel: Option<u16>,
    pub(crate) pan_id: Option<String>,
    pub(crate) extended_pan_id: Option<String>,
    pub(crate) network_key: Option<String>,
}

impl fmt::Debug for CreateNetwork {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CreateNetwork")
            .field("network_name", &self.network_name)
            .field("channel", &self.channel)
            .field("pan_id", &self.pan_id)
            .field("extended_pan_id", &self.extended_pan_id)
            .field(
                "network_key",
                &self.network_key.as_ref().map(|_| "[REDACTED]"),
            )
            .finish()
    }
}

/// The active Thread network configuration, including credentials.
///
/// Values are held in zeroizing memory and redacted from debug output. The
/// explicit exposure methods make credential reads visible at call sites.
#[derive(Clone)]
pub struct ThreadActiveDataset {
    active_dataset_tlvs: SecretString,
    network_key: Option<SecretString>,
    pskc: Option<SecretString>,
}

impl ThreadActiveDataset {
    pub(crate) fn new(
        active_dataset_tlvs: String,
        network_key: Option<String>,
        pskc: Option<String>,
    ) -> Self {
        Self {
            active_dataset_tlvs: SecretString::new(active_dataset_tlvs),
            network_key: network_key.map(SecretString::new),
            pskc: pskc.map(SecretString::new),
        }
    }

    #[must_use]
    pub fn expose_active_dataset_tlvs(&self) -> &str {
        self.active_dataset_tlvs.expose_secret()
    }

    #[must_use]
    pub fn expose_network_key(&self) -> Option<&str> {
        self.network_key
            .as_ref()
            .map(ExposeSecret::expose_secret)
            .map(String::as_str)
    }

    #[must_use]
    pub fn expose_pskc(&self) -> Option<&str> {
        self.pskc
            .as_ref()
            .map(ExposeSecret::expose_secret)
            .map(String::as_str)
    }
}

impl fmt::Debug for ThreadActiveDataset {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ThreadActiveDataset")
            .field("active_dataset_tlvs", &"[REDACTED]")
            .field(
                "network_key",
                &self.network_key.as_ref().map(|_| "[REDACTED]"),
            )
            .field("pskc", &self.pskc.as_ref().map(|_| "[REDACTED]"))
            .finish()
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadNetwork {
    pub network_name: Option<String>,
    pub pan_id: String,
    pub extended_address: String,
    pub extended_pan_id: Option<String>,
    pub channel: u16,
    pub rssi: i16,
    pub lqi: u8,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadChannelDiagnostics {
    pub channel: u16,
    pub max_rssi: Option<i16>,
    pub occupancy: Option<u16>,
    pub network_count: usize,
    pub strongest_network_rssi: Option<i16>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ThreadRadioStatistics {
    pub cca_failure_rate: Option<u16>,
    pub latest_rssi: Option<i16>,
    pub monitor_sample_count: Option<u32>,
    pub tx_total: Option<u32>,
    pub rx_total: Option<u32>,
    pub tx_retries: Option<u32>,
    pub tx_errors: Option<u32>,
    pub rx_errors: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadScan {
    pub channels: Vec<ThreadChannelDiagnostics>,
    pub networks: Vec<ThreadNetwork>,
    pub devices: Vec<ThreadMeshDevice>,
    pub statistics: ThreadRadioStatistics,
    /// Freshness and failure information for each independently collected
    /// diagnostics source.
    pub sources: Vec<ThreadScanSourceStatus>,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ThreadScanSource {
    NearbyNetworks,
    ChannelEnergy,
    ChannelUtilization,
    RadioStatistics,
    MeshDevices,
}

impl ThreadScanSource {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::NearbyNetworks => "nearby_networks",
            Self::ChannelEnergy => "channel_energy",
            Self::ChannelUtilization => "channel_utilization",
            Self::RadioStatistics => "radio_statistics",
            Self::MeshDevices => "mesh_devices",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThreadObservationState {
    Fresh,
    Stale,
    Unavailable,
}

impl ThreadObservationState {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Fresh => "fresh",
            Self::Stale => "stale",
            Self::Unavailable => "unavailable",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadScanSourceStatus {
    pub source: ThreadScanSource,
    pub state: ThreadObservationState,
    pub observed_at: Option<SystemTime>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadScanSnapshot {
    pub scan: Option<ThreadScan>,
    pub scanning: bool,
    pub completed_at: Option<SystemTime>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadMeshDevice {
    pub id: String,
    pub is_border_router: bool,
    pub extended_address: Option<String>,
    pub mesh_local_eid_iid: Option<String>,
    pub omr_ipv6_addresses: Vec<String>,
    pub hostname: Option<String>,
    pub eui64: Option<String>,
    pub role: Option<String>,
    pub full_thread_device: Option<bool>,
    pub rx_on_when_idle: Option<bool>,
    pub full_network_data: Option<bool>,
    pub rloc16: Option<String>,
    pub rloc_address: Option<String>,
    pub router_id: Option<u16>,
    pub router_count: Option<u16>,
    pub network_name: Option<String>,
    pub extended_pan_id: Option<String>,
    pub border_agent_id: Option<String>,
    pub border_agent_state: Option<String>,
    pub partition_id: Option<u32>,
    pub leader_router_id: Option<u16>,
    pub data_version: Option<u16>,
    pub stable_data_version: Option<u16>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadRuntimeConfig {
    pub rcp_device: Option<PathBuf>,
    pub agent_path: Option<PathBuf>,
    pub baud_rate: u32,
    pub thread_interface: String,
    pub infrastructure_interface: String,
    pub data_path: PathBuf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThreadRcpConfidence {
    Verified,
    Plausible,
}

impl ThreadRcpConfidence {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Verified => "verified",
            Self::Plausible => "plausible",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadRcpCandidate {
    pub path: PathBuf,
    pub confidence: ThreadRcpConfidence,
    pub match_reason: String,
    pub usb_vendor_id: Option<u16>,
    pub usb_product_id: Option<u16>,
    pub manufacturer: Option<String>,
    pub product: Option<String>,
    pub serial_number: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThreadRuntimeSnapshot {
    pub available: bool,
    pub rcp_device: Option<PathBuf>,
    pub message: Option<String>,
    pub phase: ThreadRuntimePhase,
    pub consecutive_failures: u32,
    pub restart_count: u64,
    pub next_retry_at: Option<SystemTime>,
    pub last_exit: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThreadRuntimePhase {
    Pending,
    WaitingForRcp,
    Starting,
    Ready,
    Degraded,
    Backoff,
    Stopped,
}

impl ThreadRuntimePhase {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::WaitingForRcp => "waiting_for_rcp",
            Self::Starting => "starting",
            Self::Ready => "ready",
            Self::Degraded => "degraded",
            Self::Backoff => "backoff",
            Self::Stopped => "stopped",
        }
    }
}

impl ThreadRuntimeSnapshot {
    #[must_use]
    pub fn unavailable(message: impl Into<String>) -> Self {
        Self {
            available: false,
            rcp_device: None,
            message: Some(message.into()),
            phase: ThreadRuntimePhase::WaitingForRcp,
            consecutive_failures: 0,
            restart_count: 0,
            next_retry_at: None,
            last_exit: None,
        }
    }

    #[must_use]
    pub fn ready(rcp_device: PathBuf) -> Self {
        Self {
            available: true,
            rcp_device: Some(rcp_device),
            message: None,
            phase: ThreadRuntimePhase::Ready,
            consecutive_failures: 0,
            restart_count: 0,
            next_retry_at: None,
            last_exit: None,
        }
    }
}
