#ifndef EXTRITTIO_DEVICE_STATUS_H
#define EXTRITTIO_DEVICE_STATUS_H

#define EXTRITTIO_STATUS_ONLINE  "online"
#define EXTRITTIO_STATUS_OFFLINE "offline"
#define EXTRITTIO_STATUS_WARNING "warning"

#endif /* EXTRITTIO_DEVICE_STATUS_H */
