version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /apps/frontend
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    groups:
      container-images:
        patterns: ["*"]
