[package]
name = "extrittio-simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
extrittio-common = { version = "0.1.0", path = "../../../crates/common" }
extrittio-sdk = { version = "0.1.0", path = "../sdk" }
prost = "0.13"
rand = "0.9"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zenoh = { version = "1", default-features = false, features = ["transport_tcp", "transport_tls"] }
