[package]
name = "extrittio-rpi"
version = "0.1.0"
edition = "2024"

[dependencies]
extrittio-common = { path = "../../../common" }
extrittio-sdk = { path = "../sdk" }
zenoh = { version = "1", default-features = false, features = ["transport_tcp", "transport_tls"] }
prost = "0.13"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", features = ["stream"] }
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1"
libc = "0.2"
