/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(extrittio_DeviceTelemetry, extrittio_DeviceTelemetry, AUTO)


PB_BIND(extrittio_DeviceTelemetry_MetadataEntry, extrittio_DeviceTelemetry_MetadataEntry, AUTO)


PB_BIND(extrittio_DeviceHeartbeat, extrittio_DeviceHeartbeat, AUTO)


PB_BIND(extrittio_DeviceCommand, extrittio_DeviceCommand, 2)


PB_BIND(extrittio_DeviceCommand_ParamsEntry, extrittio_DeviceCommand_ParamsEntry, AUTO)


PB_BIND(extrittio_DeviceCommandResponse, extrittio_DeviceCommandResponse, 2)


PB_BIND(extrittio_ShadowReport, extrittio_ShadowReport, 2)


PB_BIND(extrittio_ShadowDelta, extrittio_ShadowDelta, 2)


PB_BIND(extrittio_ShadowGet, extrittio_ShadowGet, AUTO)


PB_BIND(extrittio_DeviceLog, extrittio_DeviceLog, 2)



