DROP INDEX IF EXISTS idx_network_observed_hosts_tenant_analyzer;
DROP INDEX IF EXISTS idx_zones_tenant_id;
DROP INDEX IF EXISTS idx_alerts_tenant_device_status;
DROP INDEX IF EXISTS idx_rules_tenant_target;
DROP INDEX IF EXISTS idx_ota_deployments_tenant_device_id;
DROP INDEX IF EXISTS idx_device_logs_tenant_device_created;
DROP INDEX IF EXISTS idx_telemetry_tenant_device_received;
DROP INDEX IF EXISTS idx_command_history_tenant_device_created;
DROP INDEX IF EXISTS idx_firmware_updates_tenant_id;
DROP INDEX IF EXISTS idx_devices_tenant_fleet;
DROP INDEX IF EXISTS idx_devices_tenant_status;
DROP INDEX IF EXISTS idx_devices_tenant_id;
DROP INDEX IF EXISTS idx_fleets_tenant_id;
DROP INDEX IF EXISTS idx_device_types_tenant_id;
DROP INDEX IF EXISTS idx_api_keys_tenant_id;
DROP INDEX IF EXISTS idx_users_tenant_id;

ALTER TABLE network_observed_hosts DROP COLUMN tenant_id;
ALTER TABLE zones DROP COLUMN tenant_id;
ALTER TABLE alerts DROP COLUMN tenant_id;
ALTER TABLE rule_cooldowns DROP COLUMN tenant_id;
ALTER TABLE rule_conditions DROP COLUMN tenant_id;
ALTER TABLE rule_actions DROP COLUMN tenant_id;
ALTER TABLE rules DROP COLUMN tenant_id;
ALTER TABLE ota_deployments DROP COLUMN tenant_id;
ALTER TABLE firmware_blobs DROP COLUMN tenant_id;
ALTER TABLE device_certificates DROP COLUMN tenant_id;
ALTER TABLE device_configs DROP COLUMN tenant_id;
ALTER TABLE device_shadows DROP COLUMN tenant_id;
ALTER TABLE device_logs DROP COLUMN tenant_id;
ALTER TABLE telemetry DROP COLUMN tenant_id;
ALTER TABLE command_history DROP COLUMN tenant_id;
ALTER TABLE firmware_updates DROP COLUMN tenant_id;
ALTER TABLE devices DROP COLUMN tenant_id;
ALTER TABLE fleets DROP COLUMN tenant_id;
ALTER TABLE device_types DROP COLUMN tenant_id;
ALTER TABLE api_keys DROP COLUMN tenant_id;
ALTER TABLE users DROP COLUMN tenant_id;

DROP TABLE organizations;
