/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and obtain a JWT token. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ca/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the CA certificate. */
        get: operations["get_ca_certificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary statistics. */
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all device types. */
        get: operations["list_device_types"];
        put?: never;
        /** Create a new device type. */
        post: operations["create_device_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a device type by ID. */
        delete: operations["delete_device_type"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List devices with optional filtering. */
        get: operations["list_devices"];
        put?: never;
        /** Create a new device. */
        post: operations["create_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a device by ID. */
        get: operations["get_device"];
        /** Update a device. */
        put: operations["update_device"];
        post?: never;
        /** Delete a device. */
        delete: operations["delete_device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the device certificate bundle (cert + private key + CA cert).
         * @description The private key is only returned once — after download the key is cleared
         *     from the database.  Subsequent calls will return 410 Gone if the key has
         *     already been retrieved.  Use the `/regenerate` endpoint to issue a new
         *     certificate if the key was lost.
         */
        get: operations["get_device_certificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/certificate/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate a device certificate. */
        post: operations["regenerate_device_certificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/certificate/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status of a device certificate (without the private key). */
        get: operations["get_device_certificate_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commands for a device. */
        get: operations["list_commands"];
        put?: never;
        /** Send a command to a device. */
        post: operations["send_command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the configuration for a device. */
        get: operations["get_config"];
        /** Update the configuration for a device (merge semantics). */
        put: operations["update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get logs for a device. */
        get: operations["get_device_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/ota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an OTA firmware update on a device. */
        post: operations["trigger_ota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/ota-deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OTA deployments for a device. */
        get: operations["list_ota_deployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart a device. */
        post: operations["restart_device"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the device shadow (desired, reported, delta). */
        get: operations["get_shadow"];
        put?: never;
        post?: never;
        /** Reset a device shadow to empty state. */
        delete: operations["delete_shadow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/shadow/desired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the desired state of a device shadow. */
        put: operations["update_desired"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/shadow/reported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update the reported state of a device shadow. */
        put: operations["update_reported"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get telemetry data for a device. */
        get: operations["get_device_telemetry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firmware-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List firmware updates. */
        get: operations["list_firmware_updates"];
        put?: never;
        /** Register a firmware update (URL-based, no file upload). */
        post: operations["create_firmware_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firmware-updates/next-version/{device_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the next auto-generated version for a device type. */
        get: operations["get_next_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firmware-updates/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload firmware binary as multipart form data. */
        post: operations["upload_firmware_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firmware-updates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a firmware update. */
        delete: operations["delete_firmware_update"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firmware-updates/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a firmware binary blob. */
        get: operations["download_firmware_blob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all fleets. */
        get: operations["list_fleets"];
        put?: never;
        /** Create a new fleet. */
        post: operations["create_fleet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a fleet by ID. */
        delete: operations["delete_fleet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users. */
        get: operations["list_users"];
        put?: never;
        /** Create a new user. */
        post: operations["create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user by ID. */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change a user's password. */
        put: operations["change_password"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — always returns 200 if the process is running. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — returns 200 only if the database is reachable. */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CaCertificateResponse: {
            certificate_pem: string;
            created_at: string;
            fingerprint: string;
        };
        ChangePasswordRequest: {
            password: string;
        };
        CommandResponse: {
            command: string;
            created_at: string;
            device_id: string;
            id: string;
            params: {
                [key: string]: unknown;
            };
            response_payload?: {
                [key: string]: unknown;
            } | null;
            status: string;
            updated_at: string;
        };
        ConfigResponse: {
            config: {
                [key: string]: unknown;
            };
            device_id: string;
            updated_at: string;
        };
        CreateUserRequest: {
            password: string;
            username: string;
        };
        DashboardStats: {
            /** Format: int64 */
            active_devices: number;
            /** Format: int64 */
            offline_devices: number;
            /** Format: int64 */
            total_devices: number;
            /** Format: int64 */
            total_messages: number;
        };
        DeviceCertificateResponse: {
            ca_pem: string;
            certificate_pem: string;
            created_at: string;
            expires_at: string;
            fingerprint: string;
            private_key_pem: string;
        };
        DeviceCertificateStatusResponse: {
            created_at: string;
            expires_at: string;
            fingerprint: string;
        };
        DeviceResponse: {
            /** Format: int32 */
            device_type_id: number;
            device_type_name: string;
            firmware: string;
            /** Format: int32 */
            fleet_id?: number | null;
            fleet_name?: string | null;
            id: string;
            last_seen: string;
            last_seen_at?: string | null;
            name: string;
            status: string;
            uptime: string;
            /** Format: int32 */
            uptime_seconds: number;
        };
        DeviceTypeResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        /** @description Standard error response body. */
        ErrorBody: {
            error: string;
        };
        FirmwareUpdateResponse: {
            branch?: string | null;
            build_timestamp?: string | null;
            changelog?: string | null;
            ci_run_url?: string | null;
            commit_sha?: string | null;
            created_at: string;
            description?: string | null;
            /** Format: int32 */
            device_type_id: number;
            device_type_name: string;
            /** Format: int32 */
            file_size?: number | null;
            filename?: string | null;
            has_blob: boolean;
            /** Format: int32 */
            id: number;
            sha256?: string | null;
            source: string;
            url: string;
            version: string;
        };
        FleetResponse: {
            /** Format: int64 */
            device_count: number;
            /** Format: int32 */
            id: number;
            name: string;
        };
        HealthResponse: {
            status: string;
        };
        LogResponse: {
            created_at: string;
            device_id: string;
            /** Format: int32 */
            id: number;
            level: string;
            message: string;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["UserResponse"];
        };
        NewDeviceRequest: {
            /** Format: int32 */
            device_type_id: number;
            firmware?: string | null;
            /** Format: int32 */
            fleet_id?: number | null;
            name: string;
        };
        NewDeviceTypeRequest: {
            name: string;
        };
        NewFirmwareUpdateRequest: {
            description?: string | null;
            /** Format: int32 */
            device_type_id: number;
            sha256?: string | null;
            url: string;
            version?: string | null;
        };
        NewFleetRequest: {
            name: string;
        };
        NextVersionResponse: {
            next_version: string;
        };
        OtaDeploymentResponse: {
            completed_at?: string | null;
            device_id: string;
            error_message?: string | null;
            /** Format: int32 */
            firmware_update_id: number;
            firmware_version: string;
            /** Format: int32 */
            id: number;
            initiated_at: string;
            status: string;
        };
        PaginatedResponse_DeviceResponse: {
            data: {
                /** Format: int32 */
                device_type_id: number;
                device_type_name: string;
                firmware: string;
                /** Format: int32 */
                fleet_id?: number | null;
                fleet_name?: string | null;
                id: string;
                last_seen: string;
                last_seen_at?: string | null;
                name: string;
                status: string;
                uptime: string;
                /** Format: int32 */
                uptime_seconds: number;
            }[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PaginatedResponse_DeviceTypeResponse: {
            data: {
                /** Format: int32 */
                id: number;
                name: string;
            }[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PaginatedResponse_FirmwareUpdateResponse: {
            data: {
                branch?: string | null;
                build_timestamp?: string | null;
                changelog?: string | null;
                ci_run_url?: string | null;
                commit_sha?: string | null;
                created_at: string;
                description?: string | null;
                /** Format: int32 */
                device_type_id: number;
                device_type_name: string;
                /** Format: int32 */
                file_size?: number | null;
                filename?: string | null;
                has_blob: boolean;
                /** Format: int32 */
                id: number;
                sha256?: string | null;
                source: string;
                url: string;
                version: string;
            }[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PaginatedResponse_FleetResponse: {
            data: {
                /** Format: int64 */
                device_count: number;
                /** Format: int32 */
                id: number;
                name: string;
            }[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PaginatedResponse_OtaDeploymentResponse: {
            data: {
                completed_at?: string | null;
                device_id: string;
                error_message?: string | null;
                /** Format: int32 */
                firmware_update_id: number;
                firmware_version: string;
                /** Format: int32 */
                id: number;
                initiated_at: string;
                status: string;
            }[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PaginatedResponse_UserResponse: {
            data: {
                /** Format: int32 */
                id: number;
                role: string;
                username: string;
            }[];
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        PaginationParams: {
            /** Format: int64 */
            limit?: number | null;
            /** Format: int64 */
            offset?: number | null;
        };
        ReadyResponse: {
            database: string;
            status: string;
        };
        SendCommandRequest: {
            command: string;
            params?: {
                [key: string]: string;
            } | null;
        };
        ShadowResponse: {
            delta: {
                [key: string]: unknown;
            };
            desired: {
                [key: string]: unknown;
            };
            device_id: string;
            reported: {
                [key: string]: unknown;
            };
            updated_at: string;
            /** Format: int32 */
            version: number;
        };
        TelemetryResponse: {
            /** Format: float */
            battery_level?: number | null;
            custom_json?: string | null;
            device_id: string;
            /** Format: float */
            humidity?: number | null;
            /** Format: int32 */
            id: number;
            received_at: string;
            /** Format: float */
            temperature?: number | null;
        };
        TriggerOtaRequest: {
            /** Format: int32 */
            firmware_update_id: number;
        };
        UpdateDeviceRequest: {
            /** Format: int32 */
            device_type_id?: number | null;
            firmware?: string | null;
            /** Format: int32 */
            fleet_id?: number | null;
            name?: string | null;
        };
        UserResponse: {
            /** Format: int32 */
            id: number;
            role: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_ca_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CA certificate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaCertificateResponse"];
                };
            };
            /** @description CA certificate not initialized */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    list_device_types: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of device types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DeviceTypeResponse"];
                };
            };
        };
    };
    create_device_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDeviceTypeRequest"];
            };
        };
        responses: {
            /** @description Device type created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTypeResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_device_type: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device type ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device type deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Devices still reference this type */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete the default type */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_devices: {
        parameters: {
            query?: {
                status?: string | null;
                search?: string | null;
                fleet_id?: number | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DeviceResponse"];
                };
            };
        };
    };
    create_device: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDeviceRequest"];
            };
        };
        responses: {
            /** @description Device created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description Device updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_device_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device certificate bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCertificateResponse"];
                };
            };
            /** @description Private key already downloaded */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device or certificate not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regenerate_device_certificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certificate regenerated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCertificateResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_device_certificate_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certificate status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null | components["schemas"]["DeviceCertificateStatusResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_commands: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (default 50, max 500). */
                limit?: number | null;
                /** @description Filter by command status. */
                status?: string | null;
            };
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of commands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"][];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_command: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendCommandRequest"];
            };
        };
        responses: {
            /** @description Command sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Configuration updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_device_logs: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (default 100, max 1000). */
                limit?: number | null;
                /** @description Filter by log level (DEBUG, INFO, WARN, ERROR). */
                level?: string | null;
                /** @description Only return records after this timestamp (RFC 3339 or YYYY-MM-DDTHH:MM:SS). */
                since?: string | null;
            };
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogResponse"][];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_ota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerOtaRequest"];
            };
        };
        responses: {
            /** @description OTA update triggered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device or firmware not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_ota_deployments: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated OTA deployment history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_OtaDeploymentResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restart_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart command sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_shadow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device shadow */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_shadow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shadow reset */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Shadow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_desired: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Shadow updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_reported: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Shadow updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShadowResponse"];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_device_telemetry: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (default 50, max 1000). */
                limit?: number | null;
                /** @description Only return records after this timestamp (RFC 3339 or YYYY-MM-DDTHH:MM:SS). */
                since?: string | null;
                /** @description Only return records before this timestamp (RFC 3339 or YYYY-MM-DDTHH:MM:SS). */
                before?: string | null;
            };
            header?: never;
            path: {
                /** @description Device ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryResponse"][];
                };
            };
            /** @description Device not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_firmware_updates: {
        parameters: {
            query?: {
                /** @description Filter by device type. */
                device_type_id?: number | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of firmware updates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_FirmwareUpdateResponse"];
                };
            };
        };
    };
    create_firmware_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewFirmwareUpdateRequest"];
            };
        };
        responses: {
            /** @description Firmware update created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmwareUpdateResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_next_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device type ID */
                device_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next version string */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextVersionResponse"];
                };
            };
        };
    };
    upload_firmware_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Multipart form: device_type_id (required), version (optional), description (optional), file (required) */
        requestBody?: {
            content: {
                "multipart/form-data": unknown;
            };
        };
        responses: {
            /** @description Firmware uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmwareUpdateResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Version already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_firmware_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Firmware update ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Firmware update deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Firmware update not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download_firmware_blob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Firmware update ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Firmware binary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Firmware not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_fleets: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of fleets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_FleetResponse"];
                };
            };
        };
    };
    create_fleet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewFleetRequest"];
            };
        };
        responses: {
            /** @description Fleet created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_fleet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fleet ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fleet not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_UserResponse"];
                };
            };
        };
    };
    create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
}
