CREATE TABLE zones (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    geometry_type TEXT NOT NULL,
    geometry_json TEXT NOT NULL,
    color TEXT NOT NULL DEFAULT '#4A90D9',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
