[package]
name = "extrittio-openthread-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
getrandom = "0.4"
nix = { version = "0.31", features = ["net", "poll", "signal", "process", "socket"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "charset", "http2", "json", "rustls-no-provider", "system-proxy"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = { version = "4.9", default-features = false }
tempfile = "3"
thiserror = "2"
tracing = "0.1"
zbus = { version = "5.18", features = ["blocking-api"] }
zeroize = "1"
